modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/owmii/powah/issues"
license="LGPLv3"

[[mods]]
modId="powah"
version="0.0.0"
displayName="Powah"
displayURL="https://www.curseforge.com/minecraft/mc-mods/powah"
authors="owmii,Technici4n"
description='''
Various ways to generate, store and transmit FE power.
'''

[[dependencies.powah]]
    modId="forge"
    mandatory=true
    versionRange="[42.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.powah]]
    modId="architectury"
    mandatory=true
    versionRange="[5.9.0,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.powah]]
    modId="cloth_config"
    mandatory=true
    versionRange="[7.0.0,]"
    ordering="NONE"
    side="BOTH"