modLoader="javafml" 
loaderVersion="[30,)"
issueTrackerURL="https://github.com/owmii/powah/issues"

[[mods]]
modId="powah"
version="${file.jarVersion}"
displayName="Powah"
displayURL="https://www.curseforge.com/minecraft/mc-mods/powah"
authors="owmii"
description='''
Various ways to generate, store and transmit FE power.
'''

[[dependencies.powah]]
    modId="lollipop"
    mandatory=true
    versionRange="[1.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.powah]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.12,)"
    ordering="NONE"
    side="BOTH"